### ISSUE TITLE
How will it work with continious integration?

### ISSUE THREAD

**Issue by mpetkov** [samvloeberghs/protractor-gherkin-cucumberjs-angular2#52]
Based on in the instuctions, the app needs to be started with **npm start** before we can run the tests with **npm run e2e**.  What would be the best way to get this 2 step process to work with continuous integration?

**Comment by samvloeberghs** [comment]
You could serve it, if tests ok continue, if tests fail roll back!

npm start is just a way to serve the application on a webserver..


On 1 Mar 2017 22:34, "Marin Petkov" <notifications@github.com> wrote:

Based on in the instuctions, the app needs to be started with *npm start*
before we can run the tests with *npm run e2e*. What would be the best way
to get this 2 step process to work with continuous integration?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/samvloeberghs/protractor-gherkin-cucumberjs-angular2/issues/52>,
or mute the thread

**Comment by mpetkov** [comment]
Ah so it has to be deployed before it is tested...  That is unfortunate.  I am curious, how come when I use protractor, without cucumber, I am able to test it fine without serving the app?

**Comment by samvloeberghs** [comment]
how can you test a webapplication if you're not serving it..?  **That doesn't make any sense**

**Comment by mpetkov** [comment]
Sorry I used poor choice of words.  Basically what I was trying to say that by using protarcator as is, the framework was able to serve and test the app without me having to first serve the application.  However when I changed protractor to use cucumber it looks like I have to add another step to serve the app first.  It looks like this is standard so I will just have to edit my build process to accommodate.

**Comment by samvloeberghs** [comment]
@mpetkov no problemo! :) Can you point me to a reference that documents how you can use protractor to test an application that is not served? I've been using protractor for 3+ years and I'm a little but surprised by that. Never used it like that before..

**Comment by mpetkov** [comment]
Alright, after double checking my build tasks I found the issue and fixed it.  Yes, the app absolutely has to be served to be tested but the serving and testing could be combined into one gulp task which will serve the app, test it, and close it.  Here is how mgechecv did it for his seed using express:
https://github.com/mgechev/angular-seed/blob/master/tools/tasks/seed/e2e.ts
